### ISSUE TITLE
Captcha protection for hire me link

### ISSUE THREAD

**Issue by baris5d** [baris5d/homepage#2]
Bots can steal email address from hire me link so it has to be protected by captcha

**Comment by Bhasfe** [comment]
I'm working on it.

**Comment by baris5d** [comment]
#3

**Comment by baris5d** [comment]
It doesn't work properly because recaptcha.current.reset() doesn't exist when page loaded.

**Comment by baris5d** [comment]
Issue solved at https://github.com/baris5d/homepage/commit/a762582444a1814e5f4ad7e67bd6fde008d3b4b8
